// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for blog_page documents
 */
interface BlogPageDocumentData {
  /**
   * Title field in *blog_page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title
   * - **API ID Path**: blog_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Content field in *blog_page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Content
   * - **API ID Path**: blog_page.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * blog_page document from Prismic
 *
 * - **API ID**: `blog_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogPageDocumentData>,
    "blog_page",
    Lang
  >;

/**
 * Item content in *homepage → Slice zone → image → Items*
 */
export interface HomepageDocumentDataBodyImageSliceItem {
  /**
   * gallery field in *homepage → Slice zone → image → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].image.items.gallery
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  gallery: prismic.ImageField<never>;
}

/**
 * Slice for *homepage → Slice zone*
 */
export type HomepageDocumentDataBodyImageSlice = prismic.Slice<
  "image",
  Record<string, never>,
  Simplify<HomepageDocumentDataBodyImageSliceItem>
>;

/**
 * Primary content in *homepage → Slice zone → text → Primary*
 */
export interface HomepageDocumentDataBodyTextSlicePrimary {
  /**
   * Content field in *homepage → Slice zone → text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].text.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Slice for *homepage → Slice zone*
 */
export type HomepageDocumentDataBodyTextSlice = prismic.Slice<
  "text",
  Simplify<HomepageDocumentDataBodyTextSlicePrimary>,
  never
>;

type HomepageDocumentDataBodySlice =
  | HomepageDocumentDataBodyImageSlice
  | HomepageDocumentDataBodyTextSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<HomepageDocumentDataBodySlice>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = BlogPageDocument | HomepageDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPageDocument,
      BlogPageDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataBodyImageSliceItem,
      HomepageDocumentDataBodyTextSlicePrimary,
      HomepageDocumentDataBodySlice,
      AllDocumentTypes,
    };
  }
}
